services:
  - type: web
    name: lost-and-found
    runtime: python
    buildCommand: bash ./build.sh
    startCommand: gunicorn app:app --bind 0.0.0.0:$PORT --timeout 120 --workers 2
    envVars:
      - key: PYTHON_VERSION
        value: 3.13.0
      - key: PORT
        value: 10000
      - key: PYTHONUNBUFFERED
        value: "true"
    plan: starter
    scaling:
      minInstances: 1
      maxInstances: 1